
language: python
matrix:
  include:
  - name: "Python 3.7 and 3.6 on Ubuntu Bionic"
    dist: bionic  
    python:
      - "3.7"
      - "3.6"
  - name: "Python 3.5 on Ubuntu Xenial"
    dist: xenial
    python:
      - "3.5"
script: 
  - python -m unittest